name: json-processor
version: "1.0.0"
dependencies:
- base >= 4.7 && < 5
- aeson
- bytestring
- text
- optparse-applicative
- unordered-containers
- vector
- time
- split
- directory  # Adicionado para System.Directory

library:
  source-dirs: src
  exposed-modules:
    - CLI
    - Filter
    - Validation
    - Persistence
  ghc-options:
    - -XOverloadedStrings

executables:
  json-processor:
    main: Main.hs
    source-dirs: app
    ghc-options: 
      - -threaded 
      - -rtsopts 
      - -with-rtsopts=-N
      - -XOverloadedStrings
    dependencies:
      - json-processor