name:                json-processor
version:             0.1.0.0

dependencies:
- base >= 4.7 && < 5
- aeson              # Para manipulação de JSON
- bytestring         # Para I/O de arquivos eficiente
- text               # Para manipulação de texto (usado por Aeson)
- optparse-applicative # Para parsing de argumentos de linha de comando
- vector

library:
  source-dirs: src

executables:
  json-processor:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - json-processor